MoviePriceTrackerWebClient/Controllers/MovieController.cs
using MoviePriceTrackerWebClient.Helpers;
using MoviePriceTrackerWebClient.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviePriceTrackerWebClient.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            // hit my details api
            /*
            string baseUrl = CustomConfigs.MovieBaseUrl;
            string searchUrl = CustomConfigs.SearchUrl;
            searchUrl = string.Format(baseUrl, searchUrl.ToString());

            var client = new RestClient(searchUrl);
            var request = new RestRequest(Method.POST);

            // kind of json (object format)
            var data = new
            {
                query = "Jack Reacher"
            };

            request.AddJsonBody(data);

            var viewModel = client.Execute<MovieSearchModel>(request);

            return View(viewModel.Data.Results);
            */
            return View();
        }

        [HttpPost]
        public ActionResult Index(string searchbox)
        {
            string baseUrl = CustomConfigs.MovieBaseUrl;
            string searchUrl = CustomConfigs.SearchUrl;
            searchUrl = string.Format(baseUrl, searchUrl.ToString());

            var client = new RestClient(searchUrl);
            var request = new RestRequest(Method.POST);

            // kind of json (object format)
            var data = new
            {
                query = searchbox
            };

            request.AddJsonBody(data);

            var viewModel = client.Execute<MovieSearchModel>(request);

            var resData = viewModel.Data.Results;

            // checking if it is already being tracked
            foreach(MovieDetailsViewModel movieObject in resData)
            {
                movieObject.IsTracking = MovieTrackingController.TrackingMovieIds
                                            .Any(trackingId => trackingId == movieObject.Id);
            }

            return View("SearchList", resData);
        }

        // GET: Movie/Details/5
        public ActionResult Details(int id)
        {
            // hit my details api
            string baseUrl = CustomConfigs.MovieBaseUrl;
            string movieDetailsURL = CustomConfigs.DetailsUrl;
            movieDetailsURL = string.Format(movieDetailsURL, id.ToString());
            movieDetailsURL = string.Format(baseUrl, movieDetailsURL);

            var client = new RestClient(movieDetailsURL);

            // GET request
            var viewModel = client.Execute<MovieDetailsViewModel>(new RestRequest());

            return View(viewModel.Data);
        }

        // GET: Movie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Movie/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Movie/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Movie/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Movie/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MoviePriceTrackerWebClient/Views/Movie/Details.cshtml
@model MoviePriceTrackerWebClient.Models.MovieDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Movie Details</h2>

<div>
    <h4>MovieDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Overview)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Overview)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Popularity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Popularity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PosterPath)
        </dt>

        <dd>
            <image src="@Model.PosterPath" style="width:200px;height:200px;"/>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MoviePriceTrackerWebClient/Views/Movie/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@Html.Partial("SearchBox")

MoviePriceTrackerWebClient/Views/Movie/SearchBox.cshtml
<h2>Search Movie</h2>

<div class="search">
    @using (Html.BeginForm("Index", "Movie", FormMethod.Post))
    {
        <input name="searchbox" type="text" class="form-control"
                style="display:inline-block;"/>
        <input type="submit" value="Search" class="btn btn-primary"
               style="display:inline-block;"/>
    }
</div>

MoviePriceTrackerWebClient/Views/Movie/SearchList.cshtml
@model IEnumerable<MoviePriceTrackerWebClient.Models.MovieDetailsViewModel>

@{
    ViewBag.Title = "Search Results";
}

@Html.Partial("SearchBox")

<h2>Search Results</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PosterPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Overview)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Popularity)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@item.PosterPath" style="width:80px;height:120px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td width="650">
                @Html.DisplayFor(modelItem => item.Overview)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Popularity)
            </td>
            <td>
                @if (item.IsTracking)
                {
                    <button class="btn btn-success" onclick="trackMovie(this,@item.Id)">Tracking</button>
                }
                else
                {
                    <button class="btn btn-primary" onclick="trackMovie(this,@item.Id)">Track Price</button>
                }
            </td>
        </tr>
    }

</table>

@section Scripts {
    <script type="text/javascript">
        function trackMovie(btn, movieId) {
            console.log(movieId);
            console.log(btn);
            var $btn = $(btn);
            // change color + text (!!dynamically!!)
            if ($btn.hasClass('btn-primary')) {
                // ajax post call - add tracking id on server
                $.ajax({
                    type: "POST",
                    url: "http://localhost:52450/api/movieapi/trackmovie",
                    data: {
                        movieId: movieId
                    },
                    dataType: 'json',
                    success: function (response) {
                        console.log(response);
                        $(btn).text('Tracking!');
                        $(btn).removeClass('btn-primary').addClass('btn-success');
                    }
                });
            }
            else {
                // ajax post call - remove tracking id on server
                $.ajax({
                    type: "POST",
                    url: "http://localhost:52450/api/movieapi/removetracking",
                    data: {
                        movieId: movieId
                    },
                    dataType: 'json',
                    success: function (response) {
                        console.log(response);
                        $(btn).text('Track Price');
                        $(btn).removeClass('btn-success').addClass('btn-primary');
                    }
                });
            }
        }
    </script>
}